sonar.projectKey=RafalSladek_habitio
sonar.organization=rafalsladek

sonar.sources=.
sonar.exclusions=node_modules/**,playwright-report/**,test-results/**,coverage/**,.nyc_output/**,docs/**,icons/**
sonar.tests=tests
sonar.test.inclusions=tests/**/*.spec.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=tests/**,sw.js,manifest.json
